### PR TITLE
fix: define string values for enums

### PR DESCRIPTION
**Pull request by jfairley**
Defines string values for enums.

<hr>

In TypeScript, an enum is an interesting and odd struct. Take the following for instance:

```typescript
export enum ContentStatus {
  ACTIVE,
  PENDING,
  REJECTED
}
```

The literal compilation of the above enum is an object like:

```typescript
export const ContentStatus = {
  ACTIVE: 0,
  PENDING: 1,
  REJECTED: 2
}
```

However, the _keys_ of this object are what have meaning in the fusionauth api. 

The correct thing to do when using enums in this context is to define a string value like:

```typescript
export enum ContentStatus {
  ACTIVE = "ACTIVE",
  PENDING = "PENDING",
  REJECTED = "REJECTED"
}
```

so that you end up with an object literal like:

```typescript
export const ContentStatus = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  REJECTED: "REJECTED"
}
```

<hr>

I discovered this while attempting to mock (using jest) the client function `searchUsersByQuery`. Without these changes, my test compilation fails like:

Screen Shot 2020-06-01 at 5 20 50 PM

which is saying that `"ACTIVE"` is not a valid value for `ContentStatus`.

<hr>

suggested read: https://blog.logrocket.com/why-typescript-enums-suck/

### CODE REVIEW

**Comment by robotdan** [comment]
Thanks @jfairley we'll take a look. 

These domain objects are built via template, so we'll take a look and if we want to make this change it will be in the template file. 



See https://github.com/FusionAuth/fusionauth-client-builder/blob/1355ea36cbaeac2ad30abbc148eae24ef4f33c0f/src/main/client/typescript.client.ftl#L181

```
export enum ${d.type} {
  [#list d.enum as value]
    [#if global.needsConverter(d)]
  ${value.name} = "${(value.args![])[0]!value.name}"[#sep],[/#sep]
    [#else]
  ${value.name!value}[#sep],[/#sep]
    [/#if]
  [/#list]
}
```

**Comment by jfairley** [comment]
Oh nice! Should be easy peasy. It's just an edit to that else. Lemme know if you need anything!

**Comment by jfairley** [comment]
@robotdan, I've created https://github.com/FusionAuth/fusionauth-client-builder/pull/14.

**Comment by robotdan** [comment]
FusionAuth/fusionauth-client-builder#14 was merged, closing this one.

**Pull request closed without merging**
