### PR TITLE
Add http agent

### PR DESCRIPTION
**Pull request by lamuertepeluda**
Hi,

trying to address #30 

I wasn't able to run the tests.

I'm not sure how to test this does not break the browser, since http.Agent is a Node.js class.

### CODE REVIEW

**Comment by mooreds** [comment]
@lamuertepeluda Thanks very much for the PR! Sorry for the delay.

I noticed that the logic changes were intertwined with formatting changes. Hate to nitpick, but would prefer if the latter were backed out (unless, of course, we're formatting code in a way that is out of touch with typescript best practices--let us know that).

However, a bigger issue is that if `http.Agent` is a node class, maybe there's something else we can use? My brief googling didn't turn up anything, but are you aware of any options?

(You can test by pulling down https://github.com/fusionauth/fusionauth-example-node and tweaking it to use the new code branch and a path that exercises the browser. Yes, we should add automated tests :) but right now I'm testing manually. )

**Comment by mooreds** [comment]
BTW, I realized I was wrong. We do have automated tests, just not around this piece of the code (see https://github.com/FusionAuth/fusionauth-typescript-client/tree/master/test for the tests we have).

**Comment by lamuertepeluda** [comment]
Hi @mooreds ,

regarding the formatting, I will try to revert. It was probably my VSCode format-on-save plugin messing around with the formatting. But I suggest to add some .editorconfig or .prettierrc file to keep the formatting more consistent.


Thanks for providing me the link to the tests, but as you said, it does not cover this piece of code and it looks to me it is only node-based: that wouldn't help us anyway :( 

AFAIK `http.Agent` is the only way to address this kind of issue, which is basically a node issue: you won't have problems with proxy settings in a browser, but a process running behind a proxy will... :(

I just wonder if there is a way of optionally loading a dependency only when using node, or alternatively to mock `http.Agent` with an empty object in the browser, since it would not be used anyway.

**Comment by mooreds** [comment]
Makes sense. I googled around a bit and couldn't find any `http.agent` solution that presented the same API to browser and node. I'll see if I can find anything, maybe ask on a slack or two, but if you stumble across something, please share!

**Pull request closed without merging**
